# Pytorch
: 딥러닝/머신러닝 모델을 만들고 학습시키는 파이썬 라이브러리


* 텐서(tenser) : 머신러닝의 기본 구성 요소. 파이토치 기본 단위  <br>
	- 데이터를 수치적인 방식으로 표현 <br>
	-이미지는 [colour_channels, height, width] ,  3색상 채널(빨강, 초록, 파랑), 높이 x 224픽셀, 너비 x 224픽셀 로 표현 <br>
		ex) [3, 224, 224] <br>


# scalar
: 하나의 숫자이며, 텐서 용어로는 0차원 텐서를 의미 <br>



In [7]:
import torch
torch.__version__

'2.9.1+cu126'

In [8]:
#Scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [9]:
scalar.ndim #check dimensions

0

- item( ) : 텐서 안에 들어 있는 숫자 하나를 파이썬 숫자로 꺼냄 <br>
    -요소가 1개인 스칼라 텐서에서만 작동

In [10]:
scalar.item()

7

# vector 
: 1차원 텐서지만 여러개 숫자 포함 가능 <br>
-방향을 나타내는 숫자

In [11]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
vector.ndim #check the number of dimensions of vector

1

In [13]:
vector.shape #check shape of vector

torch.Size([2])

[ ] 안에 우리가 7,7 두개의 요소를 넣어놨기에 shape가 [2]

* dimension은 [ ]의 수

# matrix (행렬)
: 2차원 숫자 배열


In [14]:
#Matrix
MATRIX = torch.tensor([[7, 8], [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX.shape

torch.Size([2, 2])

깊이가 요소 2개, 너비도 요소 2개로 구성 되어 있음 -> torch.Size([2, 2])

# tensor
:n차원 숫자 배열

-임의의 숫자가 될 수 있음 <br>
-0차원 텐서는 스칼라, 1차원 텐서는 벡터

In [17]:
#Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

- dimsensions fo outer to inner
    --> TENSOR은 3x3크기의 차원 한개


* scalar, vector은 소문자. MATRIX, TENSOR은 대문자로 주로 사용

# Random tensors
 -신경망과 같은 머신러닝 모델이 텐서 내의 패턴 조작하고 찾아냄 <br>
 -머신러닝 모델은 방대한 양의 무작위 숫자 텐서로 시작하는 데이터를 조정하고 처리하며 데이터를 더 잘 표현함 <br>
 Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

 - torch.rand() : 난수 텐서 생성



In [20]:
#create a random rensor of size (3,4)
random_tensor = torch.rand(size = (3,4))  #size 매개변수 이용
random_tensor, random_tensor.dtype

(tensor([[0.8076, 0.0822, 0.5328, 0.1637],
         [0.6874, 0.6888, 0.5247, 0.3015],
         [0.5571, 0.3536, 0.3569, 0.6008]]),
 torch.float32)

*common image shape : [224, 224, 3] ([height, width, color_channels])

In [21]:
#Create a random tensor of size (224, 224, 3)
random_image_size_tansor = torch.rand(size=(224, 22,4, 3))
random_image_size_tansor.shape, random_image_size_tansor.ndim

(torch.Size([224, 22, 4, 3]), 4)

- tensor을 0 또는 1로 채우기 <br>
-> masking에서 주로 사용 (값을 0으로 지정해 모델이 학습하지 않도록 함)

- torch.zeros() : 0으로 채우기
- torch.ones( ) : 1로 채우기

In [22]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

# range 이용해 tensor 만들기

- torch.arange(start, end, step)

*Pytorch에선 torch.range() 권장 x. 오류 발생 가능

In [23]:
#create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- torch.zeros_like(input)<br>
- torch.ones_like(input) <br>
: 동일한 형태의 0 또는 1로 채워진 텐서 반환

In [24]:
#Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) #will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 텐서 데이터 유형

-대부분 텐서는 GPU 컴퓨터에 사용됨 <br>
-일반적인 기본 값: torch.float32 또는 torch.float   --> 32비트 부동 소수점 <br>
-16비트 부동 소수점(torch.float16 또는 torch.half)과 64비트 부동소수점(torch.float64 또는 torch.double)도 존재<br>
-8비트, 16비트, 32비트, 64비트 정수도 존재 <br>

-정밀도 값(8, 16, 32)이 높을수록 숫자를 표현하는 데 더 많은 세부 정보와 데이터가 사용됨<br>
-정밀도가 낮은 데이터 유형은 일반적으로 계산 속도가 빠르지만 정확도와 같은 평가 지표에서 성능이 떨어짐(계산 속도는 <br>빠르지만 정확도는 떨어짐)


- 특정 데이터 타입을 가진 텐서 생성

In [25]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None, #기본값은 None. torch.float32 또는 전달된 데이터 유형 사용
                                device=None, #기본값은 None. 기본 텐서 유형 사용
                                requires_grad= False) #True면 이 텐서에 대해 수행되는 연산들이 기록됨
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

*requires_grad : 자동미분(autograd)을 켤지 말지 정하는 옵션 <br>
    -False면 연산 추적x. 기울기 계산 안 함

Pytorch에서 흔히 접하는 문제 <br>
1. 텐서 형태 일치하지 않음
2. 데이터 유형 일치하지 않음
3. 장치 문제 - 텐서 간 계산이 동일한 장치에서 이루어지지 x ex) 하나는 CPU에 있고 다른 하나는 GPU


In [26]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) #torch.half would also work
float_16_tensor.dtype

torch.float16

# 텐서에서 정보 얻기
- 일반적인 텐서 속성들 <br>
1.shape (일부 연산엔 특정 형태 규칙 필요) <br>
2.dtype-텐서 내 요소들이 어떤 데이터 타입으로 저장되었는지<br>
3.device-텐서가 어떤 장치에 저장되는지 (일반적으로 CPU 또는 GPU) <br>



In [27]:
#create a tensor
some_tensor = torch.rand(3,4)

#Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}") #기본값 : CPU

tensor([[0.6351, 0.9107, 0.1916, 0.5876],
        [0.5663, 0.4207, 0.7109, 0.4987],
        [0.4788, 0.2491, 0.9609, 0.4369]])
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


# 텐서 조작(연산)

-딥러닝에서 데이터(이미지, 텍스트, 비디오, 오디오, 단백질 구조 등)는 텐서로 표현됨 <br>
-모델은 이러한 텐서를 조사하고 입력 데이터의 패턴을 표현하기 위해 텐서에 일련의 연산(수백만 건 이상일 수 있음)을 수행함으로써 학습함 <br>
-신경망의 기본 요소 : 덧셈, 뺄셈,, 곱셈(요소별), 분할, 행렬 곱셈 <br>

In [41]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [42]:
tensor*10

tensor([10, 20, 30])

In [43]:
#torch functions
torch.multiply(tensor, 10)


tensor([10, 20, 30])

*기호 쓰는 것이 torch.mul() 쓰는 것보다 일반적

# Matrix multiplication(행렬곱) 

@ :  파이썬에서 행렬곱셈 나타내는 기호

- 주요 규칙
1. 내부 차원 일치 <br>
(3, 2) @ (3, 2) -> 작동 x  <br>
(2, 3) @ (3, 2) -> 작동 <br>

2. 결과 행렬은 외부 차원 형태 가짐 <br>
(2, 3) @ (3, 2) -> (2, 2)



In [47]:
import torch 
tensor =  torch.tensor( [1, 2, 3] )
tensor.shape

torch.Size([3])

요쇼별 곱셈 (element-wise multiplication) : tensor * tensor --> [1*1, 2*2, 3*3]=[1, 4, 9]  <br>
행렬 곱셈 (matrix multiplication): tensor.matmul(tensor) --> [1*1 + 2*2 + 3*3]=[14]

In [48]:
tensor*tensor

tensor([1, 4, 9])

In [49]:
torch.matmul(tensor, tensor)

tensor(14)

In [50]:
tensor @ tensor

tensor(14)

# 딥러닝에서 가장 흔한 오류-형태 오류(모양 불일치)

- 전치 (주어진 텐서의 치원 바꾸는 것)
1) torch.transpose(input, dim0, dim1) - input(전치하려는 텐서), dim0 & dim1 (교환할 차원)
2) tensor.T : 텐서의 마지막 두 차원을 변경


In [51]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)


In [52]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [53]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")   #원래 형태 
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n") # 바뀐 후 
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n") #내부 차원이 일치해 행렬곱 가능
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


- torch.mm( ) = torch.matmul ( )
- torch.nn.Linear( ) : feed-forward layer / fully connected layer
