- torch.nn.Linear( ) : 입력 x와 가중치 행렬 A간의 곱셈 구현(=feed-forward layer, fully connected layer) <br>
<br>
     y= x * A**T + b
<br>
x : 레이어에 대한 입력 (딥러닝은 torch.nn.Linear()와 같은 레이어들이 서로 쌓여 있는 구조) <br>
A : 레이어에서 생성된 가중치 행렬 <br>
- 이 행렬은 처음에 난수로 시작하며, 신경망이 데이터의 패턴을 더 잘 표현하도록 학습함에 따라 조정됨 ("T"는 가중치 행렬이 전치되기 떄문) <br>
-참고 : 가중치 행렬을 나타내기 위해 W 또는 X와 같은 문자를 자주 볼 수도 있음 <br>
b : 가중치와 입력값을 약간 상쇄하기 위해 사용되는 편향<br>
y : 출력 값<br>
--> 선형 함수! <br>






In [29]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [30]:
import torch
#선형 레이어는 무작위 가중치 행렬로 시작하므로 재현 가능하도록 만듬
torch.manual_seed(42) #난수 생성의 기준값(seed) 고정
#행렬 곱셈 사용
linear = torch.nn.Linear(in_features=2, #in_features : 입력 데이터의 특성 
                         out_features=6) # out_features = 출력으로 만들 특성 
x = tensor_A
output = linear (x) #입력 x에 선형 변환을 적용 . (=output = x @ W.T + b)
print(f"Input shape : {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape : torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


# 최소값, 최대값, 평균, 합계 등 구하는 작업 (집계)

In [31]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

집계 작업 수행

In [32]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") #실수 데이터 타입 아니면 오류
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [33]:
# torch 메서드 이용
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

# positional min/max (위치 정보를 포함한 최솟값/최댓값)

torch.argmax( ) / torch.argmin( ) : 텐서의 최댓값/최솟값 발생하는 인덱스 찾기 <br>
-> 실제 값 자체가 아니라 최대/최소 값이 있는 위치만 필요한 경우에 유용

In [34]:
# create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

#최대, 최소 값의 인덱스 반환
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


# 텐서의 데이터 타입 변경

데이터 타입이 다른 텐서들의 연산 시 오류 발생 ex) torch.float64인 텐서와 torch.float32인 경우 <br>
- torch.Tensor.type(dtype=None) : dtype을 매개변수로 데이터 유형을 지정하여 텐서의 데이터타입 변경

In [35]:
#텐서 생성 후 데이터타입 확인
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [36]:
#float16 텐서 생성
tensor_int8 = tensor.type(torch.int8)
tensor_int8


tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

*숫자가 작을 수록 컴퓨터가 값을 저장하는 정밀도 낮음

#  Reshaping, stacking, squeezing and unsqueezing

텐서 내부 값 변경하지 않고 텐서의 형태나 차원만 변경


- torch.reshape(input, shape) : 입력값의 모양을 변경 (호환되는 경우) (=torch.Tensor.reshape())
- Tensor.view(shape) : 원본 텐서의 데이터를 다른 shape 으로 표현한 뷰 반환. 이때 원래 텐서와 데이터는 같음.
- torch.stack(tensors, dim=0) : 새로운 차원(dim)에 따라 일련의 tensors을 연결. 이때 쌓이는 모든 텐서는 모양이 완전히 같아야 한다.
- torch.squeeze(input) : 값이 1인 모든 차원을 제거하기 위해 input를 압축
- torch.unsqueeze(input, dim) : 지정한 dim에 크기가 1인 차원을 추가한 input을 반환
- torch.permute(input, dims) : 원본 입력 텐서를 지정한 순서(dims)대로 차원을 재배열한 뷰(view)를 반환

In [37]:
#Create a tensor
import torch
x = torch. arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [38]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape #add an extra dimension 

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [39]:
# Change view - 기존 데이터는 같지만 view 변경
z=x.view(1,7)  
x, z, z.shape


(tensor([1., 2., 3., 4., 5., 6., 7.]),
 tensor([[1., 2., 3., 4., 5., 6., 7.]]),
 torch.Size([1, 7]))

- 텐서의 view 변경은 동일한 텐서의 새 view를 생성하는 것 <bt>
-> view 변경하면 원래 텐서도 변경됨

*view : 같은 텐서를 다른 모양으로 바라보는 것

In [40]:
#z의 변화는 x를 바꿈
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [41]:
#텐서를 겹쳐 쌓기 
x_stacked = torch.stack([x, x, x, x], dim=0) 
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

텐서에서 단일 차웜 모두 제거 <br>
-> torch.squeeze( ) : 텐서의 차원이 1보다 큰 값만 갖도록 압축

In [42]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#x_shaped에서 추가 차원 삭제
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [45]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)  #unsqueeze() : 특정 인덱스에 차원이 1인 값 추가
print(f"\nNew tensor: {x_unsqueezed}")  
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


torch.permute(input, dims)를 사용하면 축(axis)의 순서를 다시 배치할 수 있는데, 이때 입력 텐서는 새로운 차원 순서를 가진 뷰(view) 로 변환

In [ ]:
x_original = torch.rand(size=(224, 224, 3))

#축 순서를 재배열하기 위해 원래 텐서 순열
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


*순열된 텐서 값은 원본 텐서 값과 동일

# 인덱싱 (텐서에서 데이터 선택)

- 인덱싱 값은 외부차원에서 내부 차원으로 이동
- x[batch][row][column]

In [47]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#대괄호 하나씩 출력
print ( f"첫 번째 대괄호: \n { x [ 0 ] } " )    #x[0] : 0번 차원(batch)에서 0번째 선택 -> 결과는 (3,3)
print ( f"두 번째 대괄호: { x [ 0 ][ 0 ] } " )  #batch 안에서 0번째 행(row) 선택
print ( f"세 번째 대괄호: { x [ 0 ][ 0 ][ 0 ] } " )   #x[0][0]   == x[0, 0]

첫 번째 대괄호: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 
두 번째 대괄호: tensor([1, 2, 3]) 
세 번째 대괄호: 1 


 이 차원의 모든 값들을 지정하기 위해 ': ' 사용 후 ' ,'사용해 다른 차원 추가

In [53]:
#0번째 차원의 모든 값& 1번째 차원의 0번째 인덱스 가져옴

x[:, 0]

tensor([[1, 2, 3]])

In [54]:
#0번째 및 1번째 차원의 모든 값 가져오지만 2번째 차원의 인덱스 1만 가져옴
x[:, :, 1]

tensor([[2, 5, 8]])

In [55]:
# 0차원의 모든 값, 1차원/2차원의 인덱스 값 중 1만 가져옴
x[:, 1, 1]

tensor([5])

# Pytorch tensor & NumPy
 NumPy : Numerical Python. 파이썬에서 다차원 배열/행열 연산 라이브러리

 - NumPy와 Pytorch가 데이터 주고받을 때 사용할 주요 방법
 1. torch.from_numpy(ndarray) - Numpy 배열을 Pytorch 텐서로 변환
 2. torch.Tensor.numpy()  - Pytorch 텐서를  Numpy 배열로 변환
 

In [58]:
# NumPy 배열을 tensor로 변환
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

*NumPy 배열을 기본적으로 float64 데이터 유형으로 생성됨 (pytorch 텐서로 변환해도 동일한 데이터 유형 유지됨) <br>
하지만 대부분 pytorch 연산은 float32 사용 <br>
-->   tensor = torch.from_numpy(array).type(torch.float32) :  NumPy 배열(float64)을 PyTorch 텐서(float64)로, 다시 PyTorch 텐서(float32)로 변환


In [59]:
#배열 변경, 텐서 유지
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

# 재현성 (무작위성에서 무작위성을 제거)

seed : 무작위성에 영향을 미치는 역할을 하는 정수
- torch.manual_seed(seed)

In [65]:
import random
RANDOM_SEED=42  #random seed 설정
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
#새 rand() 호출될 때마다 seed 리셋해야 함(안그럼 tensor_c랑 tensor_D랑 다를 수 있음)
torch.random.manual_seed(seed=RANDOM_SEED) #이 줄 주석처리 해보기 --> 주석처리하면 다르게 됨
random_tensor_D = torch.rand(3,4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# GPU에서 텐서 실행해 계산 속도 향상

-수치 연산은 기본적으로 CPU(중앙 처리 장치)에서 수행됨 <br>
-GPU(그래픽 처리 장치) - 신경망에 필요한 특정 연산(행렬 곱셈)을 수행하는 데 있어 CPU보다 훨씬 빠른 경우가 있음 <br>
-> 신경망을 훈련시킬 때 가능한 자주 사용해야 훈련 시간을 획기적으로 딘축시켜줌

1. pytorch를 GPU에서 실행

In [66]:
# pytorch가 GPU에 접근할 수 있는지 확인
torch.cuda.is_available()

True

In [68]:
#device 타입 설정
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

"cuda" --> 모든 PyTorch 코드가 사용 가능한 CUDA 장치(GPU)를 사용하도록 설정할 수 있다는 의미
* PyTorch에서는 디바이스에 구애받지 않는 코드를 작성하는 것이 best <br>
-> CPU(항상 사용 가능) 또는 GPU(사용 가능한 경우)에서 모두 실행될 수 있는 코드를 작성


In [70]:
torch.cuda.device_count() #pytorch가 접근할 수 있는 GPU 장치 개수 세기

1

*PyTorch가 사용할 수 있는 GPU 개수를 아는 것 <br>
 - >  특정 프로세스를 하나의 GPU에서 실행하고 다른 프로세스를 다른 GPU에서 실행하려는 경우에 유용

2. 텐서(및 모델)를 GPU에 배치
- to (device) : 텐서( 및 모델)을 특정 장치에 배치     *device:텐서를 배치할 대상 장치

이렇게 하는 이유 -> GPU를 사용할 수 없는 경우 장치에 구애받지 않는 코드 덕분에 CPU에서 실행됨


In [72]:
# 텐서 생성 (기본값 : CPU)
tensor = torch.tensor([1, 2, 3])

# 텐서가 GPU에 없는 것 확인
print(tensor, tensor.device)

#텐서를 GPU로 이동 (가능한 경우)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

device='cuda:0' -> 사용 가능한 0번째 GPU (GPU는 0부터 시작, 만약 GPU가 2개면 cuda:0과 cuda:1 있을것임. cuda:n까지 )

3. 텐서를 CPU로 다시 이동

-numpy를 사용해 텐서와 사용히려는 경우 텐서를 CPU로 옮기는 작업 수행 <br>
-tensor_on_gpu,numpy() 사용시 에러 <br>
- tensor.cpu( ) : 텐서를 CPU로 다시 가져와 NumPy에서 사용할 수 있게 함. <br>
-텐서를 CPU 메모리로 복사하여 CPU에서 사용가능하게 함.





In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu      #이 때 GPU 텐서의 복사본을 CPU 메모리에 반환해 원본 텐서는 여전히 GPU에 있음

array([1, 2, 3])

In [74]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# 01. PyTorch 워크플로우 기본 사항
